<template lang="pug">
    form(ref="boxForm" @submit.prevent="submit")
        nav
            input(type="checkbox" label="Structured annotation" v-model="structured")
        div.stepper(v-if="structured" v-model="step" vertical)
            div.stepper__step(:step="1" editable) 
                span Subject
                small what are you talking about?
            div.stepper__step-content(:step="1")
                input.autocomplete(
                    label="Subjects" 
                    :items="elements" item-text="id" :menuProps="{ 'z-index': 999} "
                    :value="selectedSubjects"
                    @input="$emit('boxSubjectSelection', $event)"
                    return-object multiple
                )
            div.stepper__step(:step="2" editable) 
                span Verb
                small what makes the subjects relevant?
            div.stepper__step-content(:step="2")
                input(type="text" label="Verb" v-model="verb")
            div.stepper__step(:step="3" editable) 
                span Complement
                small do you compare subjects to other data?
            div.stepper__step-content(:step="3")
                input.autocomplete(
                    label="Complements" 
                    :items="elements" item-text="id" :menuProps="{ 'z-index': 999} "
                    :value="selectedComplements"
                    @input="$emit('boxComplementSelection', $event)"
                    return-object multiple
                )
            div.stepper__step(:step="4" editable) 
                span Conclusion
                small what do you infer from this observation?
            div.stepper__step-content(:step="4")
                textarea(label="Conclusion" v-model="conclusion" placeholder="Therefore, it seems that...")
                input.combobox(type="text" label="Tags" v-model="tags" :items="previousTags" multiple)
        button(type="submit") Submit
</template>

<script>
import { Annotation } from '@/models';

/**
 * Create a new Box.
 * Boxes allow analysts to enter their annotation.
 */
export default {
    props: {
        /** The list of elements, generated by a call to getDataFromContainer */
        elements: { type: Array, required: true },
        /** The list of selected subjects */
        selectedSubjects: { type: Array, default: () => [] },
        /** The list of selected components */
        selectedComplements: { type: Array, default: () => [] },
        /** The list of existing tags in the backend's database */
        previousTags: { type: Array, default: () => [] }
    },
    data () {
        /** Whether the current annotation should be structured */
        const structured = true;
        /** Current step of the annotation process */
        const step = 1;
        /** The conclusion / free annotation */
        const conclusion = '';
        /** The verb (will be replaced) */
        const verb = '';
        /** Tags associated with the annotation */
        const tags = [];

        return {
            structured, step, conclusion, verb, tags
        }
    },
    computed: {
        /** @returns the annotation */
        theAnnotation() {
            const { selectedSubjects, selectedComplements, verb, conclusion, tags } = this;
            return new Annotation({
                subjects: selectedSubjects,
                complements: selectedComplements,
                verb, conclusion, tags,
            });
        }
    },
    methods: {
        submit() {
            this.$emit('submittingAnnotation', this.theAnnotation);
        }
    },
    watch: {
        step() {
            this.$emit('stepChanged', this.step);
        }
    }
}
</script>
