<template lang="pug">
    v-form(ref="boxForm" @submit.prevent="submit")
        v-layout(column space-between)
            v-toolbar
                v-checkbox(label="Structured annotation" v-model="structured")
            v-stepper(v-if="structured" v-model="step" vertical)
                v-stepper-step(:step="1" editable) 
                    span Subject
                    small what are you talking about?
                v-stepper-content(:step="1")
                    v-autocomplete(
                        label="Subjects" 
                        :items="elements" item-text="id" :menuProps="{ 'z-index': 999} "
                        :value="selectedSubjects"
                        @input="$emit('boxSubjectSelection', $event)"
                        return-object multiple
                    )
                v-stepper-step(:step="2" editable) 
                    span Verb
                    small what makes the subjects relevant?
                v-stepper-content(:step="2")
                    v-text-field(label="Verb" v-model="verb")
                v-stepper-step(:step="3" editable) 
                    span Complement
                    small do you compare subjects to other data?
                v-stepper-content(:step="3")
                    v-autocomplete(
                        label="Complements" 
                        :items="elements" item-text="id" :menuProps="{ 'z-index': 999} "
                        :value="selectedComplements"
                        @input="$emit('boxComplementSelection', $event)"
                        return-object multiple
                    )
                v-stepper-step(:step="4" editable) 
                    span Conclusion
                    small what do you infer from this observation?
                v-stepper-content(:step="4")
                    v-textarea(label="Conclusion" v-model="conclusion" placeholder="Therefore, it seems that...")
                    v-combobox(label="Tags" v-model="tags" :items="previousTags" multiple)
            v-btn(type="submit") Submit
</template>

<script lang="ts">
import { Vue, Prop, Component, Watch } from 'vue-property-decorator';

import { DataInput, Annotation } from '@/models';

/**
 * Create a new Box.
 * Boxes allow analysts to enter their annotation.
 * @extends Vue
 */
@Component
export default class Box extends Vue {
    /** The list of elements, generated by a call to getDataFromContainer */
    @Prop({ type: Array, required: true }) public elements!: DataInput[];
    /** The list of selected subjects */
    @Prop({ type: Array, default: () => [] }) public selectedSubjects!: any[];
    /** The list of selected components */
    @Prop({ type: Array, default: () => [] }) public selectedComplements!: any[];
    /** The list of existing tags in the backend's database */
    @Prop({ type: Array, default: () => [] }) public previousTags!: any[];

    /** Whether the current annotation should be structured */
    public structured: boolean = true;
    /** Current step of the annotation process */
    public step: number = 1;
    /** The conclusion / free annotation */
    public conclusion: string = '';
    /** The verb (will be replaced) */
    public verb: string = '';
    /** Tags associated with the annotation */
    public tags: any[] = [];

    /** @returns the annotation */
    get theAnnotation(): Annotation {
        const { selectedSubjects, selectedComplements, verb, conclusion, tags } = this;
        return new Annotation({
            subjects: selectedSubjects,
            complements: selectedComplements,
            verb, conclusion, tags,
        });
    }

    /** Sends the annotation to parents */
    public submit() {
        this.$emit('submittingAnnotation', this.theAnnotation);
    }

    @Watch('step')
    private onStepChanged() {
        this.$emit('stepChanged', this.step);
    }
}
</script>
