<template lang="pug">
    section.col-input-main
        col-input-selector(
            v-show="annotating" 
            :init="init" :offsetTop="offsetTop"  :vis="vis"
            :selectedSubjects="selectedSubjects" :selectedComplements="selectedComplements" :step="step"
            @subjectSelection="selectElementsBySelector($event)" @complementSelection="selectElementsBySelector($event, 'complement')"
        )
        col-input-overlay(
            :annotating="annotating" :elements="elements" :previousTags="previousTags"
            :selectedComplements="selectedComplements" :selectedSubjects="selectedSubjects" 
            @close="$emit('close')" @stepChanged="step = $event" @boxSubjectSelection="selectElementsByBox($event)"
            @boxComplementSelection="selectElementsByBox($event, 'complement')" @submittingAnnotation="$emit('submittingAnnotation', $event)"
        )
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator';

import ColInputSelector from '@/components/Input/Selector.vue';
import ColInputOverlay from '@/components/Input/Overlay.vue';

import { checkIfSelected } from '@/assets/utils';
import { DataInput } from '@/models';

import { SelectionCoordinates } from 'types';

/**
 * Create a new Colvis.
 * This component manages all data and communication between
 * the other subcomponents (chiefly, the Selector and the Overlay).
 * @extends Vue
 */
@Component({
    components: { ColInputOverlay, ColInputSelector },
})
export default class Main extends Vue {
    /** A query selector that identifies the visualization's container */
    @Prop({ type: String, required: true }) public vis!: string;
    /** Whether the user is annotating the visualization */
    @Prop({ type: Boolean, default: false }) public annotating!: boolean;
    /** Whether to use the dark theme for the Vuetify's components */
    @Prop({ type: Boolean, default: false }) public dark!: boolean;
    /** Whether the visualization has been initialized */
    @Prop({ type: Boolean, default: false })  public init!: boolean;
    /** The list of existing tags in the backend's database */
    @Prop({ type: Array, default: () => [] }) public previousTags!: any[];
    /** The list of elements, generated by a call to getDataFromContainer */
    @Prop({ type: Array, required: true }) public elements!: DataInput[];
    /**
     * The height in pixels of the padding-top of the container.
     * Useful when the Selector lies within elements with position absolute.
     */
    @Prop({ type: Number, default: 0 }) public offsetTop!: number;

    /** The list of selected subjects */
    public selectedSubjects: any[] = [];
    /** The list of selected components */
    public selectedComplements: any[] = [];
    /** The current step of the annotation */
    public step: number = 1;

    /**
     * Select a list of elements, based on the selection's coordinates usually sent from a Selector.
     * @param {SelectionCoordinates} coordinates selected rectangle where to search for selectable elements
     * @param {string} [pool=subject] either 'subject' or 'complement', which pool to feed with the selection
     */
    public selectElementsBySelector(coordinates: SelectionCoordinates, pool = 'subject') {
        const selectedElements = this.elements.filter((el) => {
            const elRect: ClientRect = el.domElement.getBoundingClientRect();
            return checkIfSelected(elRect, coordinates);
        });

        if (pool === 'subject') this.selectedSubjects = selectedElements;
        else this.selectedComplements = selectedElements;
    }

    /**
     * Select a list of elements.
     * @param {Array} elements a list of elements
     * @param {string} [pool=subject] either 'subject' or 'complement', which pool to feed with the selection
     */
    public selectElementsByBox(elements: DataInput[], pool = 'subject') {
        const els = elements.map((el: DataInput) => el.id);
        const selectedElements = this.elements.filter((el) => {
            return els.includes(el.id);
        });

        if (pool === 'subject') this.selectedSubjects = selectedElements;
        else this.selectedComplements = selectedElements;
    }
}
</script>
