<template lang="pug">
    aside.col-input-overlay
        nav.col-input-overlay__drawer(:class="{ annotating }" right absolute)
            header.toolbar(flat)
                button(@click="$emit('close')" icon) close
            col-input-box(
                :elements="elements" :vis="vis" :previousTags="previousTags"
                :selectedComplements="selectedComplements" :selectedSubjects="selectedSubjects"
                @stepChanged="$emit('stepChanged', $event)" @boxSubjectSelection="$emit('boxSubjectSelection', $event)"
                @boxComplementSelection="$emit('boxComplementSelection', $event)" 
                @submittingAnnotation="$emit('submittingAnnotation', $event)"
            )
</template>

<script>
import ColInputBox from '@/components/Input/Box.vue';
import { DataInput } from '@/models';

/**
 * Create a new Overlay.
 * An overlay includes the annotation box and places it within a Vuetify's navigation drawer.
 * The box is detached from the Overlay so that developers can use it outside of the context
 * of the drawer, should it be needed.
 */
export default {
    components: { ColInputBox },
    props: {
        /** Whether the user is annotating the visualization */
        annotating: { type: Boolean, default: false },
        /** Whether to use the dark theme for the Vuetify's components */
        dark: { type: Boolean, default: false },
        /** The list of elements, generated by a call to getDataFromContainer */
        elements: { type: Array, required: true },
        /** The list of selected subjects */
        selectedSubjects: { type: Array, default: () => [] },
        /** The list of selected components */
        selectedComplements: { type: Array, default: () => [] },
        /** The list of existing tags in the backend's database */
        previousTags: { type: Array, default: () => [] },
    }
}
</script>

<style lang="sass" scoped>
.col-input-overlay
    position: fixed
    top: 0
    left: 0
    width: 100%
    height: 100%
    pointer-events: none
    z-index: 900

    &__activator
        pointer-events: auto

    &__drawer
        pointer-events: auto
        padding-top: 100px
        position: absolute
        top: 0
        right: 0
        max-width: 30em
        height: 100%
        z-index: 100
        background-color: beige
        box-shadow: 0 0 5px rgba(0, 0, 0, .5)
        transform: translateX(100%)
        transition: transform .2s ease-in-out
        &.annotating
            transform: translateX(0)
</style>
