<template lang="pug">
    aside.col-input-overlay
        v-navigation-drawer(v-model="annotating" :dark="dark" width="400px" right absolute)
            v-toolbar(flat)
                v-btn(@click="$emit('close')" icon): v-icon mdi-close
            col-input-box(
                :elements="elements" :vis="vis" :previousTags="previousTags"
                :selectedComplements="selectedComplements" :selectedSubjects="selectedSubjects"
                @stepChanged="$emit('stepChanged', $event)" @boxSubjectSelection="$emit('boxSubjectSelection', $event)"
                @boxComplementSelection="$emit('boxComplementSelection', $event)" 
                @submittingAnnotation="$emit('submittingAnnotation', $event)"
            )
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator';

import ColInputBox from '@/components/Input/Box.vue';
import { DataInput } from '@/models';

/**
 * Create a new Overlay.
 * An overlay includes the annotation box and places it within a Vuetify's navigation drawer.
 * The box is detached from the Overlay so that developers can use it outside of the context
 * of the drawer, should it be needed.
 * @extends Vue
 */
@Component({
    components: { ColInputBox },
})
export default class Overlay extends Vue {
    /** Whether the user is annotating the visualization */
    @Prop({ type: Boolean, default: false }) public annotating!: boolean;
    /** Whether to use the dark theme for the Vuetify's components */
    @Prop({ type: Boolean, default: false }) public dark!: boolean;
    /** The list of elements, generated by a call to getDataFromContainer */
    @Prop({ type: Array, required: true }) public elements!: DataInput[];
    /** The list of selected subjects */
    @Prop({ type: Array, default: () => [] }) public selectedSubjects!: any[];
    /** The list of selected components */
    @Prop({ type: Array, default: () => [] }) public selectedComplements!: any[];
    /** The list of existing tags in the backend's database */
    @Prop({ type: Array, default: () => [] }) public previousTags!: any[];
}
</script>

<style lang="sass" scoped>
.col-input-overlay
    position: fixed
    top: 0
    left: 0
    width: 100%
    height: 100%
    pointer-events: none
    z-index: 900

    &__activator
        pointer-events: auto

    &__drawer
        pointer-events: auto
        padding-top: 100px
        position: absolute
        top: 0
        right: 0
        width: 20em
        height: 100%
        z-index: 100
        background-color: beige
        box-shadow: 0 0 5px rgba(0, 0, 0, .5)
</style>
